spring.application.name: Customers
spring.datasource.url: jdbc:h2:mem:customers
spring.config.import: configserver:http://localhost:8888
#spring.config.use-legacy-processing: true
spring:
  jpa:
    show-sql: true
eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka
eureka.instance.prefer-ip-address: true
