spring.application.name: Coupons
spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:coupons
spring.config.import: configserver:http://localhost:8888
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#server:
#  port: 8084
eureka:
  client:
  service-url:
  defaultZone: http://localhost:8761/eureka
eureka.instance.prefer-ip-address: true